/*
 *
 *
 *
 * ARTISTS
 *
 *
 *
 */
const artists = [
  { name: "Bruno Mars" },
  { name: "Gayle" },
  { name: "Toto" },
  { name: "Earth Wind and Fire" },
  { name: "Marvin Gaye" },
  { name: "Bill Withers" },
  { name: "The Temptations" },
  { name: "Elvis Costello" },
  { name: "Meghan Trainor" },
  { name: "Nirvana" },
  { name: "Sheryl Crow" },
  { name: "Stevie Wonder" },
  { name: "K-Ci & JoJo" },
  { name: "The Beatles" },
  { name: "Lionel Richie" },
  { name: "John Legend" },
  { name: "Blink 182" },
  { name: "Various Artists" },
  { name: "A Fine Frenzy" },
  { name: "Various Artists" },
  { name: "Elvis, Willie Nelson" },
  { name: "Lonestar" },
  { name: "Don McLean" },
  { name: "Billy Joel" },
  { name: "Shaggy" },
  { name: "Sarah McLachlan" },
  { name: "Maroon 5" },
  { name: "Pink Floyd" },
  { name: "Queen" },
  { name: "Various Artists" },
  { name: "Debussy" },
  { name: "Debussy" },
  { name: "Amos Lee" },
  { name: "Various Artists" },
  { name: "Etta James" },
  { name: "Various Artists" },
  { name: "Joseph Kosma, Various Artists" },
  { name: "Led Zeppelin" },
  { name: "Bryan McKnight" },
  { name: "Amy Winehouse" },
  { name: "Billie Eilish" },
  { name: "Ed Sheeran" },
  { name: "Enrique Iglesias" },
  { name: "Paul McCartney, The Wings" },
  { name: "Greenday" },
  { name: "Mary J. Blige" },
  { name: "Michael Jackson" },
  { name: "Christina Aguilera" },
  { name: "Beauty & The Beast, Disney" },
  { name: "Carrie Underwood" },
  { name: "Elton John" },
  { name: "Various Artists" },
  { name: "Foo Fighters" },
  { name: "Michael Jackson" },
  { name: "The Vervepipe" },
  { name: "Soundgarden" },
  { name: "The Doobie Brothers" },
  { name: "The Beatles" },
  { name: "Leona Lewis" },
  { name: "Rascall Flatts" },
  { name: "Joe Henderson" },
  { name: "Elton John" },
  { name: "Edward Heyman, Various Artists" },
  { name: "Queen" },
  { name: "Jimi Hendrix, John Mayer" },
  { name: "Brooks & Dunn" },
  { name: "Lady Gaga" },
  { name: "Bruce Springsteen" },
  { name: "Greenday" },
  { name: "Don Henley" },
  { name: "The Looking Glass" },
  { name: "Sara Bareilles" },
  { name: "Finneas" },
  { name: "Kelly Clarkson" },
  { name: "The Script" },
  { name: "Simon & Garfunkel" },
  { name: "Van Morrison" },
  { name: "Miles Davis" },
  { name: "N*Sync" },
  { name: "Mamas and the Papas" },
  { name: "Red Hot Chili Peppers" },
  { name: "Blondie" },
  { name: "Disney, Elton John, The Lion King" },
  { name: "REO Speedwagon" },
  { name: "Elvis, Various Artists" },
  { name: "Justin Timberlake" },
  { name: "Frankie Valli" },
  { name: "George Michael" },
  { name: "James Taylor" },
  { name: "Oasis" },
  { name: "Eric Clapton, Phenomenon" },
  { name: "Snow Patrol" },
  { name: "Sia" },
  { name: "Zac Brown Band" },
  { name: "Elton John, Lion King" },
  { name: "Coldplay" },
  { name: "Norah Jones" },
  { name: "Pocahontas" },
  { name: "Nirvana" },
  { name: "Norah Jones" },
  { name: "Frank Sinatra, Various Artists" },
  { name: "Dixie Midnight Runners" },
  { name: "The Beatles" },
  { name: "Bush" },
  { name: "Pink Floyd" },
  { name: "Avril Lavigne" },
  { name: "Gnarls Barkley" },
  { name: "Radiohead" },
  { name: "Florida Georgia Line" },
  { name: "King Harvest, Toploader" },
  { name: "Red Hot Chili Peppers" },
  { name: "Stephen Schwartz, Wicked" },
  { name: "Antonio Carlos Jobim" },
  { name: "The Eagles" },
  { name: "Arctic Monkeys" },
  { name: "Norah Jones" },
  { name: "The Beatles" },
  { name: "Elton John" },
  { name: "No Doubt" },
  { name: "Journey" },
  { name: "Queen" },
  { name: "Stevie Wonder" },
  { name: "Various Artists" },
  { name: "Aerosmith" },
  { name: "John Mayer" },
  { name: "Fleetwood Mac" },
  { name: "Dobie Gray" },
  { name: "Incubus" },
  { name: "Olivia Rodrigo" },
  { name: "Train" },
  { name: "Kansas" },
  { name: "The Weeknd" },
  { name: "Commodores" },
  { name: "Adele" },
  { name: "Chris Stapleton" },
  { name: "Boyz 2 Men" },
  { name: "Lionel Richie" },
  { name: "Foo Fighters" },
  { name: "Sugar Ray" },
  { name: "Poison" },
  { name: "Survivor" },
  { name: "Journey" },
  { name: "Alicia Keys" },
  { name: "Once, Theme" },
  { name: "Gorillaz" },
  { name: "Nina Simone, Various Artists" },
  { name: "Paul Simon" },
  { name: "Chris Stapleton" },
  { name: "Owl City" },
  { name: "Roberta Flack" },
  { name: "Modest Mouse" },
  { name: "Steve Miller Band" },
  { name: "Various Artists" },
  { name: "Kasey Musgraves" },
  { name: "Johnny Cash" },
  { name: "Stevie Wonder" },
  { name: "Lynyrd Skynyrd" },
  { name: "Tom Petty" },
  { name: "Garth Brooks" },
  { name: "CeeLo Green" },
  { name: "Chicago" },
  { name: "Christina Aguilera" },
  { name: "Hoagy Carmichael, Various Artists, Ray Charles" },
  { name: "The Beatles" },
  { name: "Daft Punk, Pharell" },
  { name: "Justin Beiber" },
  { name: "The Beatles" },
  { name: "Cyndi Lauper" },
  { name: "Tracy Chapman" },
  { name: "Bush" },
  { name: "Olivia Rodrigo" },
  { name: "Greenday" },
  { name: "Supertramp" },
  { name: "Elton John" },
  { name: "John Mayer" },
  { name: "Sara Bareilles" },
  { name: "Erik Satie" },
  { name: "Erik Satie" },
  { name: "Erik Satie" },
  { name: "Jeff Buckley" },
  { name: "Beyonce" },
  { name: "Dashboard Confessional" },
  { name: "Pharell" },
  { name: "Otis Redding" },
  { name: "Chicago" },
  { name: "Camila Cabello" },
  { name: "Credence Clearwater Revival" },
  { name: "Nirvana" },
  { name: "The Eagles" },
  { name: "Glass Animals" },
  { name: "Adele" },
  { name: "Lionel Richie" },
  { name: "The Beatles" },
  { name: "3 Doors Down" },
  { name: "The Beatles" },
  { name: "Train" },
  { name: "Plain White T's" },
  { name: "Outkast" },
  { name: "Radiohead" },
  { name: "Stevie Wonder" },
  { name: "The Lumineers" },
  { name: "Toto" },
  { name: "Billy Joel" },
  { name: "Blue Swede" },
  { name: "The Eagles" },
  { name: "The Animals" },
  { name: "The BeeGees" },
  { name: "Disney, Moana" },
  { name: "The Fray" },
  { name: "Audioslave" },
  { name: "R Kelly" },
  { name: "Johnny Nash" },
  { name: "Bonnie Raitt" },
  { name: "John Mayer" },
  { name: "Aerosmith" },
  { name: "Carole King" },
  { name: "Elton John" },
  { name: "Marvin Gaye" },
  { name: "Phoebe Bridgers" },
  { name: "Joan Jett" },
  { name: "Screamin Jay Hawkins" },
  { name: "Aretha Franklin" },
  { name: "Macy Gray" },
  { name: "Whitney Houston" },
  { name: "Backstreet Boys" },
  { name: "Jackson 5" },
  { name: "Death Cab for Cutie" },
  { name: "Gloria Gayner" },
  { name: "Stevie Wonder" },
  { name: "Boyz 2 Men" },
  { name: "Sam Smith" },
  { name: "Elton John" },
  { name: "Jason Mraz" },
  { name: "Dirty Dancing" },
  { name: "Alicia Keys" },
  { name: "Chicago" },
  { name: "Matchbox 20" },
  { name: "John Lennon" },
  { name: "Linkin Park" },
  { name: "Stone Temple Pilots" },
  { name: "Van Morrison" },
  { name: "Goo Goo Dolls" },
  { name: "Alanis Morrisette" },
  { name: "Bob Marley" },
  { name: "Stevie Wonder" },
  { name: "Julia Michaels" },
  { name: "Staind" },
  { name: "Alan Jackson, Jimmy Buffet" },
  { name: "Bon Jovi" },
  { name: "Billy Joel" },
  { name: "Carole King" },
  { name: "Faith Hill, Tim McGraw" },
  { name: "John Mellencamp" },
  { name: "Bob Marley" },
  { name: "Christina Perri" },
  { name: "Rick Springfield" },
  { name: "Lady Antebellum" },
  { name: "Nate Ruess, Pink" },
  { name: "Bill Withers, Grover Washington, Jr" },
  { name: "Billy Joel" },
  { name: "Bruno Mars" },
  { name: "Radiohead" },
  { name: "Queen" },
  { name: "Roberta Flack" },
  { name: "Prince" },
  { name: "Seal" },
  { name: "Sixpence None the Richer" },
  { name: "3 Doors Down" },
  { name: "Phoebe Bridgers" },
  { name: "Edith Piaf, Various Artists" },
  { name: "Lionel Richie" },
  { name: "Dixie Chicks, Stevie Nix" },
  { name: "Sam Smith" },
  { name: "Foo Fighters" },
  { name: "Silk Sonic" },
  { name: "The Beatles" },
  { name: "Disney, Frozen" },
  { name: "Marvin Gaye" },
  { name: "Al Green" },
  { name: "Journey" },
  { name: "Audioslave" },
  { name: "Madonna" },
  { name: "Hinder" },
  { name: "The Doobie Brothers" },
  { name: "Of Mice and Men" },
  { name: "Tim McGraw" },
  { name: "Ricky Martin" },
  { name: "Bon Jovi" },
  { name: "Stevie Wonder" },
  { name: "Bruno Mars" },
  { name: "The Kinks" },
  { name: "Ellie Goulding" },
  { name: "Elvis, Various Artists" },
  { name: "Rihanna" },
  { name: "Beyonce" },
  { name: "Sara Bareilles" },
  { name: "Henri Mancini, Romeo Juliet" },
  { name: "Justin Beiber" },
  { name: "Bill Withers" },
  { name: "Billie Holliday, Various Artists" },
  { name: "Adele" },
  { name: "Shania Twain" },
  { name: "Jimmy Buffet" },
  { name: "Train" },
  { name: "Bruno Mars" },
  { name: "Tom Petty" },
  { name: "Paul McCartney" },
  { name: "Billy Paul" },
  { name: "Gladys Knight" },
  { name: "Paramore" },
  { name: "Blink 182" },
  { name: "Various Artists" },
  { name: "Pink Floyd" },
  { name: "Breakfast at Tiffany's, Henri Mancini" },
  { name: "Van Morrison" },
  { name: "Billy Joel" },
  { name: "The Killers" },
  { name: "Simon & Garfunkel" },
  { name: "Stevie Wonder" },
  { name: "Various Artists" },
  { name: "Celine Dion, Theme" },
  { name: "Evanescence" },
  { name: "Billy Joel" },
  { name: "Frank Sinatra" },
  { name: "Lady Antebellum" },
  { name: "Billy Joel" },
  { name: "Frank Sinatra" },
  { name: "Alicia Keys" },
  { name: "TLC" },
  { name: "Bob Marley" },
  { name: "Chris Stapleton" },
  { name: "The Beatles" },
  { name: "Various Artists" },
  { name: "The Wallflowers" },
  { name: "Various Artists" },
  { name: "The Eagles" },
  { name: "Billy Joel" },
  { name: "Harold Arlen, Various Artists" },
  { name: "Michael Jackson" },
  { name: "Rolling Stones" },
  { name: "The Eagles" },
  { name: "The Doors" },
  { name: "Ed Sheeran" },
  { name: "Ed Sheeran" },
  { name: "Nickelback" },
  { name: "Billy Joel" },
  { name: "Credence Clearwater Revival" },
  { name: "Prince" },
  { name: "Imagine Dragons" },
  { name: "Prince" },
  { name: "The Four Tops" },
  { name: "Fleetwood Mac" },
  { name: "Johnny Cash" },
  { name: "Michael Jackson" },
  { name: "Elton John" },
  { name: "Adele" },
  { name: "Toto" },
  { name: "Outkast" },
  { name: "Sublime" },
  { name: "Rise Against" },
  { name: "Weezer" },
  { name: "Destiny's Child" },
  { name: "A Great Big World" },
  { name: "Billy Joel" },
  { name: "Nirvana, Terry Jacks" },
  { name: "Shinedown" },
  { name: "Chevelle" },
  { name: "Journey" },
  { name: "Earth Wind and Fire" },
  { name: "The White Stripes" },
  { name: "Marcy Playground" },
  { name: "Bradley Cooper, Lady Gaga" },
  { name: "The Black Crowes" },
  { name: "Sara Bareilles, The Waitress" },
  { name: "Maroon 5" },
  { name: "Billy Joel" },
  { name: "Billy Joel" },
  { name: "Stevie Wonder" },
  { name: "Lynyrd Skynyrd" },
  { name: "Stevie Wonder" },
  { name: "Night Ranger" },
  { name: "John Mayer" },
  { name: "Silk Sonic" },
  { name: "Carlos Santanna, Rob Thomas" },
  { name: "Red Hot Chili Peppers" },
  { name: "Fun" },
  { name: "Queen" },
  { name: "Adele" },
  { name: "Lewis Capaldi" },
  { name: "The Beatles" },
  { name: "Justin Beiber" },
  { name: "Simon & Garfunkel" },
  { name: "Chick Corea" },
  { name: "Led Zeppelin" },
  { name: "Muse" },
  { name: "Justin Beiber, Kid LAROI" },
  { name: "Rihanna" },
  { name: "Sam Smith" },
  { name: "The BeeGees" },
  { name: "Harold Arlen, Various Artists" },
  { name: "Seals & Croft" },
  { name: "Various Artists" },
  { name: "Maroon 5" },
  { name: "Stevie Wonder" },
  { name: "Encanto" },
  { name: "Neil Diamond" },
  { name: "Guns n' Roses" },
  { name: "Amos Lee" },
  { name: "Rise Against" },
  { name: "The Eagles" },
  { name: "The Eagles" },
  { name: "John Denver" },
  { name: "Franz Ferdinand" },
  { name: "Hozier" },
  { name: "A-ha" },
  { name: "Eric Clapton" },
  { name: "Chris Stapleton" },
  { name: "Luke Bryan" },
  { name: "Bruno Mars" },
  { name: "Lil Nas X" },
  { name: "Ed Sheeran" },
  { name: "Fleetwood Mac" },
  { name: "Breaking Benjamin" },
  { name: "Kenny Rogers" },
  { name: "Antonio Carlos Jobim, Various Artists" },
  { name: "Steve Miller Band" },
  { name: "30 Seconds to Mars" },
  { name: "The Lion King" },
  { name: "Hoobastank" },
  { name: "Chevelle" },
  { name: "Coldplay" },
  { name: "Dirty Dancing" },
  { name: "Fastball" },
  { name: "Jerome Kern" },
  { name: "Michael Jackson" },
  { name: "The Band" },
  { name: "Grease, Stocker Channing" },
  { name: "Ed Sheeran" },
  { name: "Maroon 5" },
  { name: "Leon Russell, George Benson" },
  { name: "Bob Marley" },
  { name: "Stone Sour" },
  { name: "Cyndi Lauper" },
  { name: "Elton John" },
  { name: "Zac Brown Band" },
  { name: "Alex Clare" },
  { name: "Bonnie Tyler" },
  { name: "Chris Stapleton" },
  { name: "Bruno Mars" },
  { name: "Van Morrison" },
  { name: "Norah Jones" },
  { name: "Toni Braxton" },
  { name: "Red Hot Chili Peppers" },
  { name: "Rihanna" },
  { name: "Matchbox 20" },
  { name: "Natasha Bedingfield" },
  { name: "Chris Stapleton" },
  { name: "Joe Cocker" },
  { name: "Bruno Mars, Mark Ronson" },
  { name: "Kings of Leon" },
  { name: "Amy Winehouse" },
  { name: "Billy Joel" },
  { name: "Dashboard Confessional" },
  { name: "Coldplay" },
  { name: "Darius Rucker, Old Crow Medicine Band" },
  { name: "John Mayer" },
  { name: "Queen" },
  { name: "Fun" },
  { name: "Encanto" },
  { name: "The Doobie Brothers" },
  { name: "Christina Aguilera" },
  { name: "Justin Timberlake" },
  { name: "Sublime" },
  { name: "Various Artists" },
  { name: "Marvin Gaye" },
  { name: "Tina Turner" },
  { name: "Prince" },
  { name: "Various Artists" },
  { name: "Bruno Mars" },
  { name: "3 Doors Down" },
  { name: "Billie Eilish" },
  { name: "Adele" },
  { name: "Chris Stapleton" },
  { name: "Dido" },
  { name: "John Mayer" },
  { name: "Pink Floyd" },
  { name: "The Beatles" },
  { name: "Eric Clapton" },
  { name: "Oasis" },
  { name: "The Beatles" },
  { name: "Joe Cocker, Bill Preston" },
  { name: "Tom Petty" },
  { name: "Aretha Franklin, Carole King" },
  { name: "Chris Stapleton" },
  { name: "Disney, Phil Collins, Tarzan" },
  { name: "Chicago" },
  { name: "Randy Newman, Toy Story, Disney" },
  { name: "Carole King, James Taylor" },
  { name: "The Outfields" },
  { name: "Elton John" },
];

export default artists;
